Fix kvariant CI
From https://github.com/meilisearch/charabia/actions/runs/7445878735/job/20255022744

   Run ./kvariants/bin/sync_dictionaries.sh
   /home/runner/work/_temp/23998b39-752b-4208-8978-233c8a1d6bc9.sh: line 1: ./kvariants/bin/sync_dictionaries.sh: No such file or directory
   Error: Process completed with exit code 127.

The script was moved when https://github.com/meilisearch/charabia/commit/49ee6919acf7ec676ed79394ac134ee2f533234a#diff-2a8d55e3eb61740bcff85b34a600a97afdc4c49f543e40fe04c5d22a3ff9fc65